// <auto-generated />
using System;
using MenuManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MenuManagement.Migrations
{
    [DbContext(typeof(MenuManagementContext))]
    [Migration("20240709111523_EditBattery")]
    partial class EditBattery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MenuManagement.Entity.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemData")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Dashboard",
                            NameEn = "Dashboard",
                            PermissionId = 21L,
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = 2L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Harita",
                            NameEn = "Map Management",
                            PermissionId = 22L,
                            Url = "/map"
                        },
                        new
                        {
                            Id = 3L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Kullanıcı Yönetimi",
                            NameEn = "User Management"
                        },
                        new
                        {
                            Id = 4L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Yetkiler",
                            NameEn = "Permissions",
                            ParentId = 3L,
                            PermissionId = 1L,
                            Url = "/usermanagement/permissions"
                        },
                        new
                        {
                            Id = 5L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Roller",
                            NameEn = "Roles",
                            ParentId = 3L,
                            PermissionId = 5L,
                            Url = "/usermanagement/roles"
                        },
                        new
                        {
                            Id = 6L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Kullanıcılar",
                            NameEn = "Users",
                            ParentId = 3L,
                            PermissionId = 13L,
                            Url = "/usermanagement/users"
                        },
                        new
                        {
                            Id = 7L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Organizasyon Yönetimi",
                            NameEn = "Organization Management",
                            PermissionId = 9L,
                            Url = "/organizationmanagement"
                        },
                        new
                        {
                            Id = 8L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Menü Yönetimi",
                            NameEn = "Menı Management",
                            PermissionId = 17L,
                            Url = "/menumanagement"
                        },
                        new
                        {
                            Id = 10L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Malzeme Yönetimi",
                            NameEn = "Material Management"
                        },
                        new
                        {
                            Id = 11L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Paneller",
                            NameEn = "Panels",
                            ParentId = 10L,
                            PermissionId = 27L,
                            Url = "/materialmanagement/panels"
                        },
                        new
                        {
                            Id = 12L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "İnverterlar",
                            NameEn = "Inverters",
                            ParentId = 10L,
                            PermissionId = 23L,
                            Url = "/materialmanagement/inverters"
                        },
                        new
                        {
                            Id = 13L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Bataryalar",
                            NameEn = "Batteries",
                            ParentId = 10L,
                            PermissionId = 31L,
                            Url = "/materialmanagement/batteries"
                        },
                        new
                        {
                            Id = 14L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Isı Pompaları",
                            NameEn = "Heat Pumps",
                            ParentId = 10L,
                            PermissionId = 35L,
                            Url = "/materialmanagement/heatpumps"
                        },
                        new
                        {
                            Id = 15L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Konstrüksiyonlar",
                            NameEn = "Constructions",
                            ParentId = 10L,
                            PermissionId = 39L,
                            Url = "/materialmanagement/constructions"
                        },
                        new
                        {
                            Id = 16L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Kablolar",
                            NameEn = "Cables",
                            ParentId = 10L,
                            PermissionId = 43L,
                            Url = "/materialmanagement/cables"
                        },
                        new
                        {
                            Id = 17L,
                            IsDeleted = false,
                            IsSystemData = true,
                            Name = "Elektrikli Şarj İstasyonları",
                            NameEn = "EV Charging Stations",
                            ParentId = 10L,
                            PermissionId = 47L,
                            Url = "/materialmanagement/chargingstations"
                        });
                });

            modelBuilder.Entity("MenuManagement.Entity.Menu", b =>
                {
                    b.HasOne("MenuManagement.Entity.Menu", "Parent")
                        .WithMany("ChildMenus")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MenuManagement.Entity.Menu", b =>
                {
                    b.Navigation("ChildMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
